# ==========================================================
# Projeto Carros
# Configura��o do Banco de Dados
# ==========================================================

# URL da conex�o JDBC
# Correção da URL (Apenas mude o final para terminar limpo ou com parâmetros válidos)
db.url=jdbc:mysql://localhost:3306/carros?useTimezone=true&serverTimezone=UTC

useUnicode=true&\
characterEncoding=UTF-8&\
serverTimezone=UTC&\
useSSL=false&\
allowPublicKeyRetrieval=true

# Driver JDBC
db.driver=com.mysql.cj.jdbc.Driver

# ==========================================================
# Credenciais
# ==========================================================
# Usu�rio do banco
db.user=carro

# Senha
db.password=carro123

# ==========================================================
# Explica��o dos par�metros da conex�o
# ==========================================================
#
# useUnicode=true
#   Garante que o driver trabalhe com caracteres Unicode.
#
# characterEncoding=UTF-8
#   Define UTF-8 como codifica��o da conex�o.
#
# serverTimezone=UTC
#   Evita o erro:
#   "The server time zone value '...' is unrecognized"
#
# useSSL=false
#   Desabilita SSL em ambiente de desenvolvimento.
#
# allowPublicKeyRetrieval=true
#   Evita problemas de autentica��o em algumas vers�es do MySQL 8.
#